import type { Metadata } from "next";
import Link from "next/link";

import { PageShell } from "@/components/PageShell";
import { Reveal } from "@/components/hero/Reveal";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata({
  title: "About",
  description:
    "Why TraceMint exists, what it deliberately does not claim, how it is built on GenLayer, and who to talk to about it.",
  path: "/about",
});

const REPO = "https://github.com/psycho24eth/tracemint";

const NOT_CLAIMS = [
  {
    claim: "It is not a legal claim",
    detail:
      "A notice is an automated finding reached by validator consensus. It carries no jurisdiction and no court behind it, and payment is voluntary. It does not replace a lawyer where you need one.",
  },
  {
    claim: "It is not a takedown service",
    detail:
      "A takedown erases the use and pays nobody. TraceMint exists to turn the same situation into a licence, which is what most creators actually wanted.",
  },
  {
    claim: "It is not a search engine",
    detail:
      "The agent looks at the pages you list, and it is honest about that. It is not crawling the whole web on your behalf, and it will miss copies on pages you have not named.",
  },
  {
    claim: "It is not infallible",
    detail:
      "Validators can disagree, in which case nothing is recorded and the agent tries again. They can also be wrong, which is why disputing a notice is free and judged the same way the claim was.",
  },
];

const BUILT = [
  {
    part: "One intelligent contract",
    detail:
      "Written in GenLayer's Python SDK. It holds the works, runs the judgement through validator consensus, does the fee arithmetic in integer basis points, and splits every payment 97/3 on the spot.",
  },
  {
    part: "One agent",
    detail:
      "TypeScript. Fetches the pages on a watchlist, extracts the images, and shortlists candidates with a perceptual hash. It can file a claim, but it cannot decide one.",
  },
  {
    part: "This front end",
    detail:
      "Next.js, reading the contract's public view methods directly. There is no private index and no server holding state you cannot read yourself.",
  },
];

export default function AboutPage() {
  return (
    <PageShell>
      <header className="mb-14 space-y-6">
        <p className="t-label">
          <span className="t-index mr-2">00</span>
          About
        </p>
        <h1 className="display-condensed max-w-4xl text-6xl md:text-8xl">
          Built for the
          <br />
          claim too small
          <br />
          to chase
        </h1>
        <p className="max-w-2xl text-muted-foreground">
          An illustrator finds their work on a shop page months after the fact. A lawyer costs more than the licence
          is worth. A recovery agency keeps a third of it. A takedown erases the use and pays nobody. So the usual
          answer is to do nothing — and the site owner, who would often have paid the licence up front if anyone had
          asked, ends up an infringer by accident.
        </p>
        <p className="max-w-2xl text-muted-foreground">
          TraceMint exists for that gap. It is a settlement rail for small image licences, where the finding is made
          by independent validators rather than by us, and the record is public enough that both sides can check it.
        </p>
      </header>

      <section aria-labelledby="why-chain" className="mb-16">
        <h2 id="why-chain" className="t-label mb-5 text-foreground">
          <span className="t-index mr-2">01</span>
          Why this needs a blockchain
        </h2>
        <div className="grid gap-px border border-[var(--line-strong)] bg-[var(--line-strong)] md:grid-cols-2">
          <div className="flex flex-col gap-3 bg-background p-6">
            <h3 className="display-wide text-base">The question that decides it</h3>
            <p className="text-sm text-muted-foreground">
              Why would a site owner voluntarily pay a notice generated by a robot? If the verdict came from our own
              server, they wouldn&apos;t — and they would be right not to. It would be one company&apos;s opinion
              about their page, produced by a model they cannot inspect, with a bill attached.
            </p>
          </div>
          <div className="flex flex-col gap-3 bg-background p-6">
            <h3 className="display-wide text-base">What GenLayer changes</h3>
            <p className="text-sm text-muted-foreground">
              Independent validators each read the live page, weigh it against terms the creator published before the
              scan, and vote. The agreed verdict and its reasoning are a transaction anyone can open in the explorer.
              Nobody is asked to trust us — they are shown something they can check.
            </p>
          </div>
        </div>
        <p className="mt-6 max-w-2xl text-sm text-muted-foreground">
          Other chains can hold the money and the terms but cannot read a web page or weigh{" "}
          <em>is this the same picture</em>. A centralised AI service can do the reading but cannot make its
          judgement checkable. GenLayer&apos;s consensus over non-deterministic work is the piece that makes an AI
          verdict something a stranger can rely on, and that is the whole product.
        </p>
      </section>

      <section aria-labelledby="honest" className="mb-16">
        <h2 id="honest" className="t-label mb-5 text-foreground">
          <span className="t-index mr-2">02</span>
          What TraceMint is not
        </h2>
        <p className="mb-8 max-w-2xl text-muted-foreground">
          Automated copyright notices have a bad name, and mostly they have earned it. Here is what this does not
          pretend to be.
        </p>
        <dl className="grid gap-px border border-[var(--line-strong)] bg-[var(--line-strong)] sm:grid-cols-2">
          {NOT_CLAIMS.map((item, index) => (
            <Reveal key={item.claim} delay={index * 60}>
              <div className="flex h-full flex-col gap-2 bg-background p-6">
                <dt className="display-wide text-base">{item.claim}</dt>
                <dd className="text-sm text-muted-foreground">{item.detail}</dd>
              </div>
            </Reveal>
          ))}
        </dl>
      </section>

      <section aria-labelledby="built" className="mb-16">
        <h2 id="built" className="t-label mb-5 text-foreground">
          <span className="t-index mr-2">03</span>
          How it is built
        </h2>
        <dl className="border-t border-line">
          {BUILT.map((item) => (
            <div key={item.part} className="grid gap-2 border-b border-line py-5 md:grid-cols-12 md:gap-8">
              <dt className="display-wide text-sm leading-tight md:col-span-4">{item.part}</dt>
              <dd className="text-sm text-muted-foreground md:col-span-8">{item.detail}</dd>
            </div>
          ))}
        </dl>
        <p className="mt-6 max-w-2xl text-sm text-muted-foreground">
          All of it is open source. The{" "}
          <Link href="/docs" className="t-link">
            developer docs
          </Link>{" "}
          list every method and who may call it, and the{" "}
          <a href={REPO} target="_blank" rel="noreferrer" className="t-link">
            repository
          </a>{" "}
          has the contract, the agent and this site.
        </p>
      </section>

      <section aria-labelledby="state" className="mb-16">
        <h2 id="state" className="t-label mb-5 text-foreground">
          <span className="t-index mr-2">04</span>
          Where it stands today
        </h2>
        <div className="grid gap-px border border-[var(--line-strong)] bg-[var(--line-strong)] sm:grid-cols-3">
          <div className="flex flex-col gap-2 bg-background p-6">
            <span className="chip chip-mint">Working</span>
            <p className="text-sm text-muted-foreground">
              Works register, the agent scans, validators agree, notices issue, licences settle, earnings withdraw,
              disputes resolve. All on chain.
            </p>
          </div>
          <div className="flex flex-col gap-2 bg-background p-6">
            <span className="chip chip-signal">Testnet</span>
            <p className="text-sm text-muted-foreground">
              GenLayer Studio Next. Test GEN for network fees is free from the faucet in the app, so you can try the
              whole flow without buying anything.
            </p>
          </div>
          <div className="flex flex-col gap-2 bg-background p-6">
            <span className="chip">No paying users yet</span>
            <p className="text-sm text-muted-foreground">
              The mechanism is proven; the economics are not. What a scan costs on real network fees has never been
              measured, and we would rather say so than guess.
            </p>
          </div>
        </div>
      </section>

      <section aria-labelledby="contact" className="border-t border-line pt-10">
        <h2 id="contact" className="display-wide mb-3 text-2xl">
          Talk to us
        </h2>
        <p className="max-w-2xl text-muted-foreground">
          TraceMint was built by{" "}
          <a href="https://github.com/psycho24eth" target="_blank" rel="noreferrer" className="t-link">
            psycho24eth
          </a>{" "}
          for the GenLayer Agent Tank hackathon, and it is still being worked on. The fastest way to reach us about a
          bug, a wrong notice, or a removal request is the{" "}
          <a href={`${REPO}/issues`} target="_blank" rel="noreferrer" className="t-link">
            issue tracker
          </a>
          . If you want to see it work before reading anything else, the{" "}
          <Link href="/judges" className="t-link">
            five-minute walkthrough
          </Link>{" "}
          runs the whole flow on a funded test wallet.
        </p>
      </section>
    </PageShell>
  );
}
